# Generated by Django 6.0.2 on 2026-02-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sajuresult',
            name='scores_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='strongest_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='weakest_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
