# Generated by Django 6.0.2 on 2026-02-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sajuresult_scores_json_sajuresult_strongest_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sajuresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='sajuresult',
            name='mbti',
            field=models.CharField(choices=[('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('INTJ', 'INTJ'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('INTP', 'INTP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ')], max_length=10),
        ),
    ]
