# Generated by Django 6.0.2 on 2026-02-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sajuresult_options_alter_sajuresult_mbti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sajuresult',
            name='scores_json',
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='scores_10',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='scores_5',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
