# Generated by Django 6.0.2 on 2026-02-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sajuresult_scores_json_sajuresult_scores_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sajuresult',
            name='strongest_group',
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='element_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='housing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='identity_core',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='job',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='location_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='love',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='lucky_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='money',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='name',
            field=models.CharField(default='이름없음', max_length=50),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='today_actions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='today_fortune',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sajuresult',
            name='scores_10',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sajuresult',
            name='scores_5',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sajuresult',
            name='weakest_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
