# Generated by Django 6.0.2 on 2026-02-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_sajuresult_strongest_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sajuresult',
            name='hidden_engine',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='management_gap',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sajuresult',
            name='safety_line',
            field=models.TextField(blank=True),
        ),
    ]
