# Generated by Django 6.0.2 on 2026-02-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sajuresult_hidden_engine_sajuresult_management_gap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sajuresult',
            name='weapons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
