# Generated by Django 6.0.2 on 2026-02-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sajuresult_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sajuresult',
            name='sub_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
